### ISSUE TITLE
segfault on Debian 10(testing)

### ISSUE THREAD

**Issue by claudiuion** [theinvisible/openfortigui#64]
When I try to connect to one of my VPN profiles as a regular user I receive the following error:
kernel: openfortigui[4835]: segfault at 8 ip 0000560415ad0f94 sp 00007ffc3facc370 error 4 in openfortigui[560415a91000+d5000]
kernel: Code: 8b 07 83 f8 01 76 0f 48 8d 7c 24 20 e8 35 c2 ff ff 48 8b 7c 24 20 48 8b 47 10 48 85 c0 0f 84 eb 09 00 00 48 8b 4c 24 10 31 d2 <8b> 49 08 eb 13 0f 1f 80 00 00 00 00 48 89 c2 48 8b 40 08 48 85 c0

It works fine after I copy the profiles under /root/.openfortigui/vpnprofiles

This is how is intended to work?

**Comment by theinvisible** [comment]
There is a fix underway that hopefully correct this problem.

The problem is the different behavior of sudo between debian and ubuntu and a bug in openfortigui that dont passes the config path to starting vpn processes. Stay tuned.

**Comment by theinvisible** [comment]
The new Release 0.7.2.2 should fix it now, please have a try.

**Comment by claudiuion** [comment]
is still present on 0.7.2.2

Nov 22 19:54:12 kernel: openfortigui[4989]: segfault at 8 ip 0000562f8664afd4 sp 00007ffeab1cd0d0 error 4 in openfortigui[562f8660b000+d5000]
Nov 22 19:54:12 kernel: Code: 8b 07 83 f8 01 76 0f 48 8d 7c 24 20 e8 35 c2 ff ff 48 8b 7c 24 20 48 8b 47 10 48 85 c0 0f 84 eb 09 00 00 48 8b 4c 24 10 31 d2 <8b> 49 08 eb 13 0f 1f 80 00 00 00 00 48 89 c2 48 8b 40 08 48 85 c0

**Comment by cdstg** [comment]
same for me if I copy the user profile to the /root/.openfortigui/vpnprofiles it works else I get a seg fault

**Comment by cdstg** [comment]
Oh forgot also debian buster

**Comment by fdimuccio** [comment]
Same in Ubuntu 19.10:

`[  757.652285] openfortigui[9204]: segfault at 8 ip 00005599169dcc74 sp 00007ffc86096d80 error 4 in openfortigui[559916992000+e9000]
[  757.652289] Code: 20 8b 07 83 f8 01 76 0f 48 8d 7c 24 20 e8 44 bb ff ff 48 8b 7c 24 20 48 8b 47 10 48 85 c0 0f 84 da 05 00 00 48 8b 34 24 31 c9 <8b> 56 08 eb 13 0f 1f 80 00 00 00 00 48 89 c1 48 8b 40 08 48 85 c0`

As mentioned by @cdstg copying the user profile to /root/ fixes the problem

**Comment by numahell** [comment]
Same in Ubuntu 19.04 and OpenFortiGUI 0.8.0, though it had worked well end of July (pretty sure it was the same version of OpenFortiGUI).

Unfortunately, copying user profile to `/root/.openfortigui/vpnprofiles` did not work, neither copying them to `/etc/openfortigui/vpnprofiles`.

I have these messages in profile logs:

```
INFO:   Start tunnel.
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway (HTTP status code).
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

**Comment by a-parhom** [comment]
Also having same issue in Ubuntu 19.10.

**Comment by Dyrcona** [comment]
I encountered this for for the first time on Ubuntu 19.10 today.  It looks like the issue is caused by changes to the policy defaults for sudo on Debian 10+ and Ubuntu 19.10+.

I have made a pullrequest that resolves this issue for me. More testing, particularly on unaffected distros would be appreciated:

https://github.com/theinvisible/openfortigui/pull/92

**Comment by theinvisible** [comment]
Hi,
there is now a new build 0.8.1 which has a optional flag in Settings that enables the workaround via -E sudo flag. Just enable the setting an try again.
Thanks so far for your feedback.
Cheers
Rene

**Comment by Dyrcona** [comment]
Version 0.8.1 with the option enabled, fixes the issue for me.
